---
title: "Day 5 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
library(ggplot2)
library(reshape2)
options(scipen = 999)
```

```{r}
input<-read_lines("Day5Sample.txt")
input<-str_replace(input," -> ",",")
```

Because start at 1 instead of 0, add 1.
```{r}
vents<-lapply(input,function(x){as.numeric(unlist(str_split(x,",")))+1 })
```

Quickly find the max x & max y and create the matrix:
```{r}
mx<-0
my<-0
for(i in 1:length(vents)){
  mx<-max(mx,vents[[i]][1],vents[[i]][3])
  my<-max(my,vents[[i]][2],vents[[i]][4])}
hvac<-matrix(0,ncol=mx,nrow=my)
  
```

So, just add 1 for everywhere where there's a horizontal or vertical line:

```{r}
for(i in 1:length(vents)){
  v<-vents[[i]]
  if(v[1]==v[3]||v[2]==v[4]){
    hvac[v[2]:v[4],v[1]:v[3]]<-hvac[v[2]:v[4],v[1]:v[3]]+1}}
```
```{r}
part1<-length(which(hvac>=2))
part1
```


```{r,echo=FALSE}
gr<-melt(hvac)
basicgraph<-ggplot(data=gr,aes(y=Var1,x=Var2,fill=value))+
  geom_tile()+
  scale_fill_gradient(low="white", high="black") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")+
  scale_y_reverse()+
  coord_fixed()
basicgraph
```

## Part 2
Add in the diagonals

```{r}
hvac<-matrix(0,ncol=mx,nrow=my)
for(i in 1:length(vents)){
  v<-vents[[i]]
  ##horizontals and verticals
  if(v[1]==v[3]||v[2]==v[4]){
    hvac[v[2]:v[4],v[1]:v[3]]<-hvac[v[2]:v[4],v[1]:v[3]]+1
    ## because I can't figure out how to generalize this right now
  }else{
    if(v[1]<=v[3]&&v[2]<=v[4]){
      for(j in 0:abs(v[2]-v[4])){hvac[(v[2]+j),(v[1]+j)]<-hvac[(v[2]+j),(v[1]+j)]+1}
    }else if(v[1]>=v[3]&&v[2]<=v[4]){
      for(j in 0:abs(v[2]-v[4])){hvac[(v[2]+j),(v[1]-j)]<-hvac[(v[2]+j),(v[1]-j)]+1}
    }else if(v[1]<=v[3]&&v[2]>=v[4]){
      for(j in 0:abs(v[2]-v[4])){hvac[(v[2]-j),(v[1]+j)]<-hvac[(v[2]-j),(v[1]+j)]+1}
    }else if(v[1]>=v[3]&&v[2]>=v[4]){
      for(j in 0:abs(v[2]-v[4])){hvac[(v[2]-j),(v[1]-j)]<-hvac[(v[2]-j),(v[1]-j)]+1}
    }else{cat("something went wrong\n")}}}
```

```{r}
part2<-length(which(hvac>=2))
part2
```

```{r,echo=FALSE}
gr<-melt(hvac)
basicgraph<-ggplot(data=gr,aes(y=Var1,x=Var2,fill=value))+
  geom_tile()+
  scale_fill_gradient(low="white", high="black") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")+
  scale_y_reverse()+
  coord_fixed()
basicgraph
```
