---
title: "Day 19 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
library(ggplot2)
library(rgl)
options(scipen = 999)
```

```{r}
input<-read_lines("Day19Sample.txt")
bl<-c(0,which(input==""),length(input)+1)
megascannerlist<-list()
for(i in 1:(length(bl)-1)){
  scannerlist<-list()
  for(j in (bl[i]+2):(bl[i+1]-1)){
    beacon<-as.numeric(unlist(str_split(input[j],",")))
    scannerlist<-c(scannerlist,list(beacon))}
  megascannerlist<-c(megascannerlist,list(scannerlist))}
```

## Part 1

First, this function gives me a list of the differences between all of the beacons for a scanner
```{r}
findbd<-function(x,nm){
  beacondists<-as.data.frame(matrix(ncol=13,nrow=0))
  colnames(beacondists)<-c("beacon1","beacon2","x1","y1","z1","x2","y2","z1","d")
  for(i in 1:(length(x)-1)){
    for(j in (i+1):length(x)){
      a<-list(beacon1=str_c(nm,"b",i),
              beacon2=str_c(nm,"b",j),
              x1=x[[i]][1],
              y1=x[[i]][2],
              z1=x[[i]][3],
              x2=x[[j]][1],
              y2=x[[j]][2],
              z2=x[[j]][3],
              dx=abs(x[[i]][1]-x[[j]][1]),
              dy=abs(x[[i]][2]-x[[j]][2]),
              dz=abs(x[[i]][3]-x[[j]][3]),
              d=sum(abs(x[[i]]-x[[j]])))
      beacondists<-rbind(beacondists,a)}}
beacondists}
```



Then, findtrans takes a list of overlapping distances and finds the transform from one to other

```{r}

findtrans<-function(ov){
  t1<-ov[1,]
  ### figure out if it matches the first or second 
  is1 <- nrow(ov %>% rowwise %>% filter(beacon1.x==t1$beacon1.x|| beacon2.x==t1$beacon1.x) %>% filter(beacon1.y==t1$beacon1.y||beacon2.y==t1$beacon1.y))
  ### if is1>1, then beacon1.x matches to beacon1.y
  ### if i1==1, then beacon1.x matches to beacon2.y
  
  ### so we're changing the labels so I don't go crazy...  x1 matches x1.  a is the ones we aren't transforming.  b is the one we are
  x1a <-t1$x1.x
  y1a <-t1$y1.x
  z1a <-t1$z1.x
  x2a <-t1$x2.x
  y2a <-t1$y2.x
  z2a <-t1$z2.x
  if(is1>1){
    x1b <-t1$x1.y
    y1b <-t1$y1.y
    z1b <-t1$z1.y
    x2b <-t1$x2.y
    y2b <-t1$y2.y
    z2b <-t1$z2.y
  }else{
    x1b <-t1$x2.y
    y1b <-t1$y2.y
    z1b <-t1$z2.y
    x2b <-t1$x1.y 
    y2b <-t1$y1.y
    z2b <-t1$z1.y}
  ### first find the transform
  rt<-matrix(NA,nrow=3,ncol=3)
  tr<-c(NA,NA,NA)
  ### x first
  ### x(transform) to x(stable)
  if(t1$dx.y==t1$dx.x){
    if((x1b-x1a)==(x2b-x2a)){
      rt[1,]<-c(1,0,0)
      tr[1]<-x1a-x1b
    }else{
      rt[1,]<-c(-1,0,0)
      tr[1]<-(x2a+x2b)}}
  ### x(transform) to y(stable)
  if(t1$dx.y==t1$dy.x){
    if((x1b-y1a)==(x2b-y2a)){
      rt[1,]<-c(0,1,0)
      tr[2]<-y1a-x1b
    }else{
      rt[1,]<-c(0,-1,0)
      tr[2]<-y2a+x2b}}
  ### x(transform) to z(stable)
  if(t1$dx.y==t1$dz.x){
    if((x1b-z1a)==(x2b-z2a)){
      rt[1,]<-c(0,0,1)
      tr[3]<-z1a-x1b
    }else{
      rt[1,]<-c(0,0,-1)
      tr[3]<-z2a+x2b}}
  
  ### then y
  ### y(transform) to x(stable)
  if(t1$dy.y==t1$dx.x){
    if((y1b-x1a)==(y2b-x2a)){
      rt[2,]<-c(1,0,0)
      tr[1]<-x1a-y1b
    }else{
      rt[2,]<-c(-1,0,0)
      tr[1]<-(x2a+y2b)}}
  ### y(transform) to y(stable)
  if(t1$dy.y==t1$dy.x){
    if((y1b-y1a)==(y2b-y2a)){
      rt[2,]<-c(0,1,0)
      tr[2]<-y1a-y1b
    }else{
      rt[2,]<-c(0,-1,0)
      tr[2]<-y2a+y2b}}
  ### y(transform) to z(stable)
  if(t1$dy.y==t1$dz.x){
    if((y1b-z1a)==(y2b-z2a)){
      rt[2,]<-c(0,0,1)
      tr[3]<-z1a-y1b
    }else{
      rt[2,]<-c(0,0,-1)
      tr[3]<-z2a+y2b}}
  
  ### then z
  ### z(transform) to x(stable)
  if(t1$dz.y==t1$dx.x){
    if((z1b-x1a)==(z2b-x2a)){
      rt[3,]<-c(1,0,0)
      tr[1]<-x1a-z1b
    }else{
      rt[3,]<-c(-1,0,0)
      tr[1]<-(x2a+z2b)}}
  ### z(transform) to y(stable)
  if(t1$dz.y==t1$dy.x){
    if((z1b-y1a)==(z2b-y2a)){
      rt[3,]<-c(0,1,0)
      tr[2]<-y1a-z1b
    }else{
      rt[3,]<-c(0,-1,0)
      tr[2]<-y2a+z2b}}
  ### z(transform) to z(stable)
  if(t1$dz.y==t1$dz.x){
    if((z1b-z1a)==(z2b-z2a)){
      rt[3,]<-c(0,0,1)
      tr[3]<-z1a-z1b
    }else{
      rt[3,]<-c(0,0,-1)
      tr[3]<-z2a+z2b}}
list(rt,tr)}

```


```{r}
concatbeacons<-function(bl){
  ### list of all beacons
  everybeacon<-bl[[1]]
  ### in list shows which (if any) have been added to our list.  T still isn't done.
  stillleft<-c(F,rep(T,(length(bl)-1)))
  ### list of all sensors
  sdf<-list()
  sdf<-c(sdf,list(c(0,0,0)))
  ### so we don't have to do this quite as much
  alldists<-lapply(1:length(bl),function(x){findbd(bl[[x]],str_c("s",x))})
  ### this is the list of all of the distances
  bigdist<-findbd(everybeacon,"s1")
  ### so long as not everything is done - keep going
  while(any(stillleft)){
    ### again, to cut down on this a bit
    for(i in which(stillleft==T)){
      ### find overlaps between the one that isn't done and the main list
      overlaps<-inner_join(bigdist,alldists[[i]],b="d",relationship="many-to-many") %>%
        rowwise%>%filter(dx.x==dx.y||dx.x==dy.y||dx.x==dz.y)%>%
        filter(dy.x==dx.y||dy.x==dy.y||dy.x==dz.y)
      ### if there are more than 66 overlaps - then we have our 12 points.
      if(nrow(overlaps>=66)){
        ### find the transform
        tobase<-findtrans(overlaps)
        ### translate
        moved<-lapply(bl[[i]],function(x){
          x<-as.vector(x%*%tobase[[1]]+tobase[[2]])
          x})
        ### redo "find distances" with the translated value
        fb<-findbd(moved,str_c("b",i))
        ### add that to the distance list
        bigdist<-rbind(bigdist,fb)
        ### add this to the list of every beacon and remove the ones that have already been moved.
        everybeacon<-c(everybeacon,moved)
        everybeacon<-unique(everybeacon)
        ### add the sensor (transforming 0,0,0) - which is effectively "tobase[[2]]"
        sdf<-c(sdf,list(tobase[[2]]))
        ### mark that this has been done
        stillleft[i]<-F}
      }
  }
  ### return the lists of every beacon & the list of sensors
  list(everybeacon,sdf)}

```


```{r}
p1<-concatbeacons(megascannerlist)
part1<-length(p1[[1]])
part1
```


##Part 2

Because I have a list of the sensors from the above function AND a function that takes a list of points and spits out their manhattan distances - this is trivial.

```{r}
p2<-findbd(p1[[2]],"s")
part2<-max(p2$d)
part2

```


